package by.epam_training.final_task.controller.command;

public enum CommandName {
    SIGNIN, SIGNUP, LOGOUT,TOPAYORDER, CHANGELOCALE, CHANGEORDER, CHANGEPASSWORD, CHANGEPROFILE,
    GOTOINDEXPAGE, GOTOAUTHORIZATIONPAGE, GOTOPROFILEPAGE, GOTOREGISTRATIONPAGE, GOTOACTIVEORDERSPAGE,
    GOTOARCHIVEORDERSPAGE, GOTORETURNEDORDERSPAGE, GOTOADDITIONALSERVICESPAGE, GOTOPAYMENTPAGE,
    RESERVATIONROOM, RETURNORDER, SEARCHROOMSBYCRYTERIA,RESERVATIONSERVICE, ADDNEWROOM,GOTOADDROOMPAGE,
    GOTOCHANGEROOMPAGE,CHANGEROOM,ADDNEWSERVICE,CHANGESERVICE,GOTOCHANGESERVICEPAGE,
    GOTOADDSERVICEPAGE,BLOCKSERVICE, BLOCKROOM,GOTOBLOCKEDROOMSPAGE,UNBLOCKROOM,
    SHOWMYADDITIONALSERVICEPAGE,GOTOBLOCKEDSERVICESPAGE,UNBLOCKSERVICE, UPLOADAVATAR, UPLOADROOMIMAGE,
    UPLOADSERVICEIMAGE
}
